joints:
  head_pan_joint: 0.25
  head_tilt_joint: 0.97
  torso_lift_joint: 0.3
  r_shoulder_pan_joint: -1.31
  r_shoulder_lift_joint: 1.28
  r_upper_arm_roll_joint: -1.45
  r_forearm_roll_joint: -1.13
  r_elbow_flex_joint: -0.24
  r_wrist_flex_joint: -0.19
  l_shoulder_pan_joint: 1.15
  l_shoulder_lift_joint: 0.07
  l_upper_arm_roll_joint: 1.52
  l_forearm_roll_joint: 0.64
  l_elbow_flex_joint: -1.2
  l_wrist_flex_joint: -1.49
  l_wrist_roll_joint: 3.08